#!/usr/bin/env bash

file=$1
w=$2
h=$3
x=$4
y=$5
# echo -en "\033[H\033[2J"

filename=$(basename "$(echo "$file" | tr ' ' '_')")

case "$(file --dereference --brief --mime-type -- "$1")" in
  *.iso) iso-info --no-header -l "$1" ;;
	# image/avif) CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
	# 	[ ! -f "$CACHE" ] && convert "$1" "$CACHE.jpg"
	# 	image "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1" ;;
	# image/vnd.djvu)
	# 	CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
	# 	[ ! -f "$CACHE" ] && djvused "$1" -e 'select 1; save-page-with /dev/stdout' | convert -density 200 - "$CACHE.jpg" > /dev/null 2>&1
	# 	image "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1" ;;
	# image/*) image "$1" "$2" "$3" "$4" "$5" "$1" ;;
	# text/html) lynx -width="$4" -display_charset=utf-8 -dump "$1" ;;
	# text/troff) man ./ "$1" | col -b ;;
	text/* | */xml | application/json | application/x-ndjson) bat --terminal-width "$(($4-2))" -f "$1" ;;
	# audio/* | application/octet-stream) mediainfo "$1" || exit 1 ;;
	# video/* )
exit 0

